### ISSUE TITLE
Code upload

### ISSUE THREAD

**Issue by rogan-ustc** [junkunyuan/AutoIV#1]
Could you please upload the complete code needed to reproduce Table 1: Results (MSE±Std) in low-dimensional scenarios? The code that has been uploaded so far only includes the AutoIV model and does not cover its integration with various downstream methods ( 2SLS (NN)，DeepIV，KernelIV，DeepGMM). Thank you very much!

**Comment by junkunyuan** [comment]
I apologize for the inconvenience caused. 
Unfortunately, we did not save the code for other methods. 
However, the repos for these methods are publicly available on GitHub. 
We encourage you to refer to them directly for further information and access to the code, such as KernelIV https://github.com/r4hu1-5in9h/KIV.
